export const NAME_REGEX = /^[a-zA-Z-]+$/;
export const USERNAME_REGEX = /^[a-zA-Z0-9_]+$/;
export const PHONE_REGEX = /^0\d{10}$/
export const BVN_REGEX = /^\d{11}$/
export const PASSWORD_UPPERCASE_REGEX = /[A-Z]+/
export const PASSWORD_LOWERCASE_REGEX = /[a-z]+/
export const PASSWORD_NUM_REGEX = /[0-9]+/
export const PASSWORD_SYMBOLS_REGEX = /[!@#$%^&*(”’)+,-./:;<=>?_^`{|~]+/;
export const FLOAT_ONLY_REGEX = /^[0-9.]+$/